---

- hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - raw: which /usr/bin/python || which /usr/bin/python3
      register: py_interpreter
      changed_when: py_interpreter.stdout != ""
    - set_fact:
        ansible_python_interpreter: "{{ py_interpreter.stdout }}"
    - name: Gathering Facts
      setup: #aka gather_facts

  roles:
    - ubuntu-setup
